{{/* Setting defaults if they are omitted. */}}
{{- $isOpenshiftCluster := .Capabilities.APIVersions.Has "apps.openshift.io/v1" -}}
{{- $deployDedicatedMonitoringSystem := .Values.pxbackup.deployDedicatedMonitoringSystem }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pxcentral-post-install-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    name: pxcentral-post-install-hook
    app.kubernetes.io/component: pxcentral-post-install-hook
{{- include "px-central.labels" . | nindent 4 }}
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              {{- if .Values.nodeAffinityLabel }}
              - key: {{ .Values.nodeAffinityLabel }}
                operator: Exists
              {{- else }}
              - key: pxbackup/enabled
                operator: NotIn
                values:
                - "false"
              {{- end }}
      serviceAccountName: pxcentral-apiserver
      {{- if $isOpenshiftCluster}}
      {{- else }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: pxcentral-post-setup
        image: {{ printf "%s/%s/%s:%s" .Values.images.postInstallSetupImage.registry .Values.images.postInstallSetupImage.repo .Values.images.postInstallSetupImage.imageName .Values.images.postInstallSetupImage.tag }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
          - name: LOG_LEVEL
            value: INFO
          - name: UPDATE_ADMIN_USER_PROFILE
            value: "{{ .Values.oidc.centralOIDC.updateAdminProfile }}"
          - name: K8S_SSL_ENABLED
            value: "{{ .Values.postInstallJob.sslEnabled }}"
          - name: PXC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- include "proxy.noProxyEnv" . | nindent 10 }}
      {{- if eq $deployDedicatedMonitoringSystem true }}
          - name: DEDICATED_PROMETHEUS
            value: "true"
      {{- else }}
          - name: DEDICATED_PROMETHEUS
            value: "false"
      {{- end }}
          - name: DEPLOYMENT_TYPE
            {{- if eq .Release.IsInstall true }}
            value: "install"
            {{- else }}
            value: "upgrade"
            {{- end }}
        command: ["python", "-u", "/pxcentral-post-install/pxc-post-setup.py"]
      {{- if .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- range $sec := .Values.images.pullSecrets }}
        - name: {{ $sec | quote }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }} 
  backoffLimit: 5
  activeDeadlineSeconds: 2400
