{{- $pxBackupEnabled := .Values.pxbackup.enabled | default false }}
{{- $telemetryEnabled := .Values.pxbackup.telemetry.enabled | default false }}
{{- if and (eq $pxBackupEnabled true) (eq $telemetryEnabled true) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: px-backup-log-upload-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: px-backup
    app.kubernetes.io/component: px-backup-telemetry
{{- include "px-central.labels" . | nindent 4 }}
data:
  ccm.properties: |
    {
      "product_name": "px-backup",
      "port": "8080",
      "rest_port": "9091",
      "envoy_host": "localhost",
      "envoy_port": "9092",
      "logupload": {
        "logfile_patterns": ["/var/cores/*"],
        "skip_patterns": [],
        "additional_files": [],
        "phonehome_hour_range": 8760,
        "max_chunk_size": 5242880,
        "hourly_timestamp_format": "2006010215",
        "daily_timestamp_format": "20060102",
        "compression_type": "gzip"
      },
      "bookkeeping": {
        "logupload_book_path": "/var/cache/ccm/log_upload.book",
        "logupload_map_path": "/var/cache/ccm/log_upload.map"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: px-backup-envoy-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: px-backup
    app.kubernetes.io/component: px-backup-telemetry
{{- include "px-central.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 9093
    node:
      id: "id_rest"
      cluster: "cluster_rest"
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 9092
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              scheme_header_transformation:
                scheme_to_overwrite: https
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    request_headers_to_add:
                    - header:
                        key: "product-name"
                        value: "portworx"
                    - header:
                        key: "appliance-id"
                        value: "APPLIANCE_ID_PLACEHOLDER"
                    - header:
                        key: "component-sn"
                        value: "px-backup-log-upload"
                    - header:
                        key: "product-version"
                        value: "{{ .Values.images.pxBackupImage.tag }}"
                    route:
                      cluster: pure1_cluster
                      timeout: 300s
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: pure1_cluster
        connect_timeout: 30s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: pure1_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: rest.staging-cloud-support.purestorage.com
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: rest.staging-cloud-support.purestorage.com
            common_tls_context:
              tls_certificate_sds_secret_configs:
                name: tls_sds
                sds_config:
                  path: /etc/envoy/tls_certificate_sds_secret.yaml
              validation_context:
                trusted_ca:
                  filename: /etc/ssl/certs/ca-certificates.crt
                match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: rest.staging-cloud-support.purestorage.com
  tls_certificate_sds_secret.yaml: |
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: tls_sds
        tls_certificate:
          certificate_chain:
            filename: /etc/pwx/pure1/cert
          private_key:
            filename: /etc/pwx/pure1/private_key
---
{{- end }}

