---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: portworxdiags.portworx.io
spec:
  group: portworx.io
  names:
    kind: PortworxDiag
    listKind: PortworxDiagList
    plural: portworxdiags
    shortNames:
    - pxdiag
    singular: portworxdiag
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status of the Portworx diag collection.
      jsonPath: .status.phase
      name: Status
      type: string
    - description: Age of the diag resource.
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: PortworxDiag is the Schema for the portworxdiags API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PortworxDiagSpec is the spec used to define a portworx diag.
            properties:
              portworx:
                description: Configuration for diags collection of the main Portworx
                  component.
                properties:
                  generateCore:
                    description: |-
                      Generates the core dump as well when collecting the diags. Could be useful
                      to analyze the current state of the system.
                    type: boolean
                  nodes:
                    description: |-
                      Nodes for which the diags need to be collected. If a volume selector is
                      also specified, then both the selectors will be honored and the selected
                      nodes will be a union of both selectors.
                    properties:
                      all:
                        description: Select all nodes in the Portworx cluster. If
                          set to true, other selectors are ignored.
                        type: boolean
                      ids:
                        description: Ids of the nodes to be selected.
                        items:
                          type: string
                        type: array
                      labels:
                        additionalProperties:
                          type: string
                        description: Labels of the volumes to be selected.
                        type: object
                    type: object
                  podDiags:
                    description: |-
                      Collects all the pod diags. Used to specify whether Pod diags need to be
                      collected or not.
                    type: boolean
                  volumes:
                    description: Volumes for which the diags need to be collected.
                    properties:
                      ids:
                        description: Ids of the volumes to be selected.
                        items:
                          type: string
                        type: array
                      labels:
                        additionalProperties:
                          type: string
                        description: Labels of the volumes to be selected.
                        type: object
                    type: object
                type: object
            type: object
          status:
            description: PortworxDiagStatus is the status of a portworx diag.
            properties:
              clusterUuid:
                description: UUID of the Portworx cluster. This is useful to find
                  the uploaded diags.
                type: string
              message:
                description: Optional message used to give the reason for any failure.
                type: string
              nodes:
                description: Status of the diags collection from all the selected
                  nodes.
                items:
                  description: Status of the diags collection from a single node.
                  properties:
                    message:
                      description: Optional message used to give the reason for any
                        failure.
                      type: string
                    nodeId:
                      description: ID of the node for which the diag status is reported.
                      type: string
                    status:
                      description: One word status of the diags collection on the
                        node.
                      type: string
                  type: object
                type: array
              observedGeneration:
                description: ObservedGeneration is the generation of the spec that
                  was last reconciled.
                format: int64
                type: integer
              phase:
                description: One word status of the entire diags collection job.
                type: string
              podDiags:
                description: Status of the diags collection from all the pods.
                properties:
                  message:
                    description: Optional message used to give the reason for any
                      failure.
                    type: string
                  status:
                    description: One word status of the pod diags collection.
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}