pxmonitor:
  enabled: true
  pxCentralEndpoint: 
  sslEnabled: false
  oidcClientID: pxcentral
  oidcClientSecret: ""

installCRDs: false
storkRequired: false
clusterDomain: "cluster.local"
cassandraUsername: cassandra
cassandraPassword: cassandra

persistentStorage:
  enabled: true
  storageClassName:
  cassandra:
    storage: 50Gi
  grafana:
    storage: 20Gi
  consul:
    storage: 8Gi

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true

images:
  pullSecrets:
    - docregistry-secret
  pullPolicy: Always

  cortexImage:
    registry: quay.io
    repo: cortexproject
    imageName: cortex
    tag: v1.0.0
  cassandraImage:
    registry: docker.io
    repo: bitnami
    imageName: cassandra
    tag: 3.11.6-debian-10-r153
  proxyConfigImage:
    registry: docker.io
    repo: library
    imageName: nginx
    tag: 1.17.8
  consulImage:
    registry: docker.io
    repo: bitnami
    imageName: consul
    tag: 1.8.0-debian-10-r24
  dnsmasqImage:
    registry: docker.io
    repo: pwxbuild
    imageName: go-dnsmasq
    tag: release-1.0.7
  grafanaImage:
    registry: docker.io
    repo: grafana
    imageName: grafana
    tag: 7.1.3
  prometheusImage:
    registry: quay.io
    repo: prometheus
    imageName: prometheus
    tag: v2.7.1
  prometheusConfigReloadImage:
    registry: quay.io
    repo: coreos
    imageName: configmap-reload
    tag: v0.0.1
  prometheusConfigReloadrImage:
    registry: quay.io
    repo: coreos
    imageName: prometheus-config-reloader
    tag: v0.34.0
  prometheusOperatorImage:
    registry: quay.io
    repo: coreos
    imageName: prometheus-operator
    tag: v0.34.0
  pxMonitorPostInstallSetup:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-monitor-post-install-setup
    tag: 1.0.0-dev
  memcachedMetricsImage:
    registry: quay.io
    repo: prometheus
    imageName: memcached-exporter
    tag: v0.4.1
  memcachedIndexImage:
    registry: docker.io
    repo: library
    imageName: memcached
    tag: 1.5.7-alpine
  memcachedImage:
    registry: docker.io
    repo: library
    imageName: memcached
    tag: 1.5.12-alpine