name: portworx
version: 8.1.0
description: A Helm chart for installing Portworx on Kubernetes.
kubeVersion: ">=1.26.0-0"
appVersion: "3.5.2"
apiVersion: v1
keywords:
  - Storage
  - ICP
  - IKS
  - persistent disk
  - pvc
  - cloud native storage
  - persistent storage
  - portworx
  - amd64
  - Commercial
home: https://www.purestorage.com/products/cloud-native-applications/portworx.html
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/k8s-porx.png
