name: portworx
version: 2.9.1
description: A Helm chart for installing Portworx on Kubernetes.
tillerversion: ">=2.9.0"
home: https://portworx.com/
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/px-logo.png
