name: portworx
version: 6.0.0
description: A Helm chart for installing Portworx on Kubernetes.
kubeVersion: ">=1.26.0-0"
appVersion: "3.2.1"
apiVersion: v1
keywords:
  - Storage
  - ICP
  - IKS
  - persistent disk
  - pvc
  - cloud native storage
  - persistent storage
  - portworx
  - amd64
  - Commercial
home: https://portworx.com/
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/k8s-porx.png
